// Generated by gencpp from file node_robot_msgs/agent_task_2.msg
// DO NOT EDIT!


#ifndef NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_2_H
#define NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_2_H

#include <ros/service_traits.h>


#include <node_robot_msgs/agent_task_2Request.h>
#include <node_robot_msgs/agent_task_2Response.h>


namespace node_robot_msgs
{

struct agent_task_2
{

typedef agent_task_2Request Request;
typedef agent_task_2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct agent_task_2
} // namespace node_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::node_robot_msgs::agent_task_2 > {
  static const char* value()
  {
    return "507b103286c30709359161b3b51d9c4a";
  }

  static const char* value(const ::node_robot_msgs::agent_task_2&) { return value(); }
};

template<>
struct DataType< ::node_robot_msgs::agent_task_2 > {
  static const char* value()
  {
    return "node_robot_msgs/agent_task_2";
  }

  static const char* value(const ::node_robot_msgs::agent_task_2&) { return value(); }
};


// service_traits::MD5Sum< ::node_robot_msgs::agent_task_2Request> should match 
// service_traits::MD5Sum< ::node_robot_msgs::agent_task_2 > 
template<>
struct MD5Sum< ::node_robot_msgs::agent_task_2Request>
{
  static const char* value()
  {
    return MD5Sum< ::node_robot_msgs::agent_task_2 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_robot_msgs::agent_task_2Request> should match 
// service_traits::DataType< ::node_robot_msgs::agent_task_2 > 
template<>
struct DataType< ::node_robot_msgs::agent_task_2Request>
{
  static const char* value()
  {
    return DataType< ::node_robot_msgs::agent_task_2 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::node_robot_msgs::agent_task_2Response> should match 
// service_traits::MD5Sum< ::node_robot_msgs::agent_task_2 > 
template<>
struct MD5Sum< ::node_robot_msgs::agent_task_2Response>
{
  static const char* value()
  {
    return MD5Sum< ::node_robot_msgs::agent_task_2 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_robot_msgs::agent_task_2Response> should match 
// service_traits::DataType< ::node_robot_msgs::agent_task_2 > 
template<>
struct DataType< ::node_robot_msgs::agent_task_2Response>
{
  static const char* value()
  {
    return DataType< ::node_robot_msgs::agent_task_2 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_2_H
