// Generated by gencpp from file node_robot_msgs/agent_task_1Request.msg
// DO NOT EDIT!


#ifndef NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1REQUEST_H
#define NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_robot_msgs
{
template <class ContainerAllocator>
struct agent_task_1Request_
{
  typedef agent_task_1Request_<ContainerAllocator> Type;

  agent_task_1Request_()
    : task_id(0)  {
    }
  agent_task_1Request_(const ContainerAllocator& _alloc)
    : task_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _task_id_type;
  _task_id_type task_id;





  typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> const> ConstPtr;

}; // struct agent_task_1Request_

typedef ::node_robot_msgs::agent_task_1Request_<std::allocator<void> > agent_task_1Request;

typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Request > agent_task_1RequestPtr;
typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Request const> agent_task_1RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'node_robot_msgs': ['/home/apeng/yp/privatespace/my_ws/src/node_robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01f8cf8853582efbb17391a60263fd03";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01f8cf8853582efbULL;
  static const uint64_t static_value2 = 0xb17391a60263fd03ULL;
};

template<class ContainerAllocator>
struct DataType< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_robot_msgs/agent_task_1Request";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 task_id\n\
";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agent_task_1Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_robot_msgs::agent_task_1Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_robot_msgs::agent_task_1Request_<ContainerAllocator>& v)
  {
    s << indent << "task_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.task_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1REQUEST_H
