// Generated by gencpp from file node_robot_msgs/agent_task_1Response.msg
// DO NOT EDIT!


#ifndef NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1RESPONSE_H
#define NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_robot_msgs
{
template <class ContainerAllocator>
struct agent_task_1Response_
{
  typedef agent_task_1Response_<ContainerAllocator> Type;

  agent_task_1Response_()
    : ret(false)  {
    }
  agent_task_1Response_(const ContainerAllocator& _alloc)
    : ret(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> const> ConstPtr;

}; // struct agent_task_1Response_

typedef ::node_robot_msgs::agent_task_1Response_<std::allocator<void> > agent_task_1Response;

typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Response > agent_task_1ResponsePtr;
typedef boost::shared_ptr< ::node_robot_msgs::agent_task_1Response const> agent_task_1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace node_robot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'node_robot_msgs': ['/home/apeng/yp/privatespace/my_ws/src/node_robot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2cc9e9d8c464550ULL;
  static const uint64_t static_value2 = 0x830df49c160979adULL;
};

template<class ContainerAllocator>
struct DataType< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_robot_msgs/agent_task_1Response";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool  ret\n\
\n\
";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agent_task_1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_robot_msgs::agent_task_1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_robot_msgs::agent_task_1Response_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1RESPONSE_H
