// Generated by gencpp from file node_robot_msgs/agent_task_1.msg
// DO NOT EDIT!


#ifndef NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1_H
#define NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1_H

#include <ros/service_traits.h>


#include <node_robot_msgs/agent_task_1Request.h>
#include <node_robot_msgs/agent_task_1Response.h>


namespace node_robot_msgs
{

struct agent_task_1
{

typedef agent_task_1Request Request;
typedef agent_task_1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct agent_task_1
} // namespace node_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::node_robot_msgs::agent_task_1 > {
  static const char* value()
  {
    return "507b103286c30709359161b3b51d9c4a";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1&) { return value(); }
};

template<>
struct DataType< ::node_robot_msgs::agent_task_1 > {
  static const char* value()
  {
    return "node_robot_msgs/agent_task_1";
  }

  static const char* value(const ::node_robot_msgs::agent_task_1&) { return value(); }
};


// service_traits::MD5Sum< ::node_robot_msgs::agent_task_1Request> should match 
// service_traits::MD5Sum< ::node_robot_msgs::agent_task_1 > 
template<>
struct MD5Sum< ::node_robot_msgs::agent_task_1Request>
{
  static const char* value()
  {
    return MD5Sum< ::node_robot_msgs::agent_task_1 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_robot_msgs::agent_task_1Request> should match 
// service_traits::DataType< ::node_robot_msgs::agent_task_1 > 
template<>
struct DataType< ::node_robot_msgs::agent_task_1Request>
{
  static const char* value()
  {
    return DataType< ::node_robot_msgs::agent_task_1 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::node_robot_msgs::agent_task_1Response> should match 
// service_traits::MD5Sum< ::node_robot_msgs::agent_task_1 > 
template<>
struct MD5Sum< ::node_robot_msgs::agent_task_1Response>
{
  static const char* value()
  {
    return MD5Sum< ::node_robot_msgs::agent_task_1 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_robot_msgs::agent_task_1Response> should match 
// service_traits::DataType< ::node_robot_msgs::agent_task_1 > 
template<>
struct DataType< ::node_robot_msgs::agent_task_1Response>
{
  static const char* value()
  {
    return DataType< ::node_robot_msgs::agent_task_1 >::value();
  }
  static const char* value(const ::node_robot_msgs::agent_task_1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODE_ROBOT_MSGS_MESSAGE_AGENT_TASK_1_H
