// Generated by gencpp from file node_robot_msgs/robot_info_report.msg
// DO NOT EDIT!


#ifndef NODE_ROBOT_MSGS_MESSAGE_ROBOT_INFO_REPORT_H
#define NODE_ROBOT_MSGS_MESSAGE_ROBOT_INFO_REPORT_H

#include <ros/service_traits.h>


#include <node_robot_msgs/robot_info_reportRequest.h>
#include <node_robot_msgs/robot_info_reportResponse.h>


namespace node_robot_msgs
{

struct robot_info_report
{

typedef robot_info_reportRequest Request;
typedef robot_info_reportResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_info_report
} // namespace node_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::node_robot_msgs::robot_info_report > {
  static const char* value()
  {
    return "64872e7e5a7ad222489d3e9f403efca1";
  }

  static const char* value(const ::node_robot_msgs::robot_info_report&) { return value(); }
};

template<>
struct DataType< ::node_robot_msgs::robot_info_report > {
  static const char* value()
  {
    return "node_robot_msgs/robot_info_report";
  }

  static const char* value(const ::node_robot_msgs::robot_info_report&) { return value(); }
};


// service_traits::MD5Sum< ::node_robot_msgs::robot_info_reportRequest> should match 
// service_traits::MD5Sum< ::node_robot_msgs::robot_info_report > 
template<>
struct MD5Sum< ::node_robot_msgs::robot_info_reportRequest>
{
  static const char* value()
  {
    return MD5Sum< ::node_robot_msgs::robot_info_report >::value();
  }
  static const char* value(const ::node_robot_msgs::robot_info_reportRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_robot_msgs::robot_info_reportRequest> should match 
// service_traits::DataType< ::node_robot_msgs::robot_info_report > 
template<>
struct DataType< ::node_robot_msgs::robot_info_reportRequest>
{
  static const char* value()
  {
    return DataType< ::node_robot_msgs::robot_info_report >::value();
  }
  static const char* value(const ::node_robot_msgs::robot_info_reportRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::node_robot_msgs::robot_info_reportResponse> should match 
// service_traits::MD5Sum< ::node_robot_msgs::robot_info_report > 
template<>
struct MD5Sum< ::node_robot_msgs::robot_info_reportResponse>
{
  static const char* value()
  {
    return MD5Sum< ::node_robot_msgs::robot_info_report >::value();
  }
  static const char* value(const ::node_robot_msgs::robot_info_reportResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::node_robot_msgs::robot_info_reportResponse> should match 
// service_traits::DataType< ::node_robot_msgs::robot_info_report > 
template<>
struct DataType< ::node_robot_msgs::robot_info_reportResponse>
{
  static const char* value()
  {
    return DataType< ::node_robot_msgs::robot_info_report >::value();
  }
  static const char* value(const ::node_robot_msgs::robot_info_reportResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NODE_ROBOT_MSGS_MESSAGE_ROBOT_INFO_REPORT_H
