(cl:defpackage node_robot_msgs-srv
  (:use )
  (:export
   "AGENT_TASK_1"
   "<AGENT_TASK_1-REQUEST>"
   "AGENT_TASK_1-REQUEST"
   "<AGENT_TASK_1-RESPONSE>"
   "AGENT_TASK_1-RESPONSE"
   "AGENT_TASK_2"
   "<AGENT_TASK_2-REQUEST>"
   "AGENT_TASK_2-REQUEST"
   "<AGENT_TASK_2-RESPONSE>"
   "AGENT_TASK_2-RESPONSE"
   "ROBOT_INFO_REPORT"
   "<ROBOT_INFO_REPORT-REQUEST>"
   "ROBOT_INFO_REPORT-REQUEST"
   "<ROBOT_INFO_REPORT-RESPONSE>"
   "ROBOT_INFO_REPORT-RESPONSE"
  ))

